# ===========================================
# Per-site configuration (encrypted secrets)
# ===========================================
# Version : Sat Feb 21 05:54:01 AM EST 2026
SITE="example.com"

# SSH connection
REMOTE_USER="example"
REMOTE_HOST="whm01.example.com"

# Remote paths
REMOTE_PATH="/home/example.com/"

# Include/Ignore directories (relative to REMOTE_PATH)
INCLUDE_DIRS="public_html"
IGNORE_DIRS=""

# Database credentials (encrypted)
DB_USER="jA0ECQMI1AuUm8C//Vr/0kkBw0ug8RLFV2+Kc7m/k66yiO1tdjZa9qcaQDjZbZ9J38NVr3rA7TdWSuRSN/hweYF6O8RTTQu8RYPh+oh8Q50ke5cltZnVF/BR"
DB_PASS="jA0ECQMI97PRnSRukq3/0kUBg6ZvJdhwjHJUmS4MxDTcozDKZIBIdc47jQF0xUV10uw/PbbEqYDlcf3R7o3guI2FudbRJpqmIBW7/Rgn9sUc6kfcgxY="
DB_HOST="jA0ECQMIgNYDGS1OaXX/0j8BIxjni8oI2HmMVBb0r6YmIbprvrWHh1/0QEJzek+IWLGTZ5XHJm+kpXCPLrqOA7PqVFWvPoAPzMfveOYwzVY="
DB_NAME="jA0ECQMIHb6SIQEotWb/0kkBt9vNOT8YFoUleRyu/IhigsGaqhylb/ZWkeNr1MIst91Z7tz8HcjrrBqaX1ZTOJ34xw1KB6We/h4NX8qY3Q10/uc7t5gDkb9S"
DB_PREFIX="jA0ECQMItKwL9CI8E0j/0jsBqFi8mpyXt6nA29Cpst/Eof9Xu4A+zXKjHol0oOKXEpYHemSdhS6kZftyRn6M4LhbjMuBjnCapoyPbQ=="

# Local backup directories
LOCAL_SYNC_PATH="/mnt/raid01/example.com"
LOCAL_ARCHIVE_PATH="/mnt/raid03/example.com"
LOCAL_SQL_PATH="/database"
LOCAL_SQL_FILE="example.com.sql"
LOCAL_DOCUMENT_ROOT="/public_html"

# Retention policy
LOCAL_ARCHIVE_RETENTION_DAYS="7"
RESTIC_RETENTION_DAYS="30"
LOG_RETENTION_DAYS="30"

# AWS S3 / RESTIC settings (encrypted)
AWS_ACCESS_KEY_ID="jA0ECQMIWro1W2pXtGv/0koBko7EEq7/YkOk5PLW2g5iF6aVtqHCwsgz7RPNlvLxVpgiJILugf8BaeD05lJoHKrp6RicJ4vaOshKBHi1egJjdvt+cSJE0BIoAQ=="
AWS_SECRET_ACCESS_KEY="jA0ECQMIKr4sP39zSgT/0l4BJ1KnBuhp+eUCfDj0jPQOHyxQeqsjeUOs7CZEt/jwQ4PZNPvWsL0hICBY+Nn5gN+S2sLAEuKFH3wZ9OOVSJ7JBKwHCKKGXv2VZtnyEE2nsd+/Trh1jhMak6lJm3BB"
AWS_S3_BUCKET="jA0ECQMIIPTm1WPw2Tj/0kQBWPBF2sFjeOWB4x04GM4Q3L4fuMU4dbMdMn20qIKJIyzP1hU9iaxawuPTm7N2R85085rgd3jTPQaT8OjtYRJJ94lXHw=="
AWS_REGION="jA0ECQMIg5hH4/EV5y3/0kIB7Lg96pq9fAZ9gWx57ugcalpkN286aCUsRUimUBE4Oc/5LKUijeR874RDJNT/iCJoG0B5wCq4QOyDx5ejllPH4D8="
AWS_S3_PATH="jA0ECQMItchxzGxP4+f/0koBr7Z8ziAM7Fh4V1uSL4PiZI0DxEFXIu7L/tLa/TgLAaQeXHBlRHoxFGGTFK0L6RsaQfcw7UHlPMyTs2v/yzxbwqN/AqVFtsv+KQ=="
AWS_RESTIC_PASSWORD="jA0ECQMItII1opVij4X/0nQBp93hgAwE/MAC2uqjPOE8Nveo9+oUC55lmyD259rWmzEZF6GsFyc98z7UQ/SzKa20PwntyrngHna/xgqcg7Cpw73uWjyCNYUEbJ4yvK6BpvNNKmfKTx0JDGqVQgKqRBySCsmbtkVbkKuHArFqtJRJURvSXw=="

# Virus / Malware Detection
CLAMAV_ENABLE="y"
MALDET_ENABLE="y"
MALDET_IGNORE_IMAGES="y"
WORDFENCE_ENABLE="y"
WORDFENCE_VULN_ENABLE="y"
WORDFENCE_ENABLE_DB="y"
WORDFENCE_DB_REMOVE_POST=""
UPLOADS_PHP_ENABLE="y"
LOCAL_ARCHIVE="y"
UPLOADS_PHP_CHECKSUMS_UNEXPECTED_FILES=""
PLUGIN_CHECKSUMS="y"
THEME_CHECKSUMS="y"
WORDPRESS_CHECKSUMS="y"

WORDPRESS_CHECKSUMS_UNEXPECTED_FILES="
wp-content/mu-plugins/et-safe-mode/SupportCenterSafeModeDisablePlugins.php:d6236dbadd78cd25859182df8068366ef07785f528253ba5c90d5b8bcd1e4aa9
wp-content/mu-plugins/SupportCenterMUAutoloader.php:4443eb23e8464ff5f467f0fea2df459f0f51f5bae3aef2cea05429e289e4ec34
wp-config.php:ebe710a2f0972be6803011d010f8a0ee13dbedb6ce4215e8bca8d5ba1a949d2b
wp-content/advanced-cache.php:30db645e69cf77b4246bb85082fbf3faa6379ff5f796ab40a0c118d948728838
.htaccess:ea34a0af4ae915c271639bb4e5caf27f69d619d3214aebf26414a06b948508e7
.user.ini:4422c2d28526597b2c37846e4fd1a0784c46fd8f01b373001cd75407dee089e9
php.ini:4422c2d28526597b2c37846e4fd1a0784c46fd8f01b373001cd75407dee089e9
"

WORDPRESS_CHECKSUMS_ALLOWED_MISSING=""

WORDPRESS_CHECKSUMS_IGNORE_PATH="
wp-content/wp-rocket-config
wp-content/et-cache
wp-content/wflogs
wp-content/cache
"

# Reporting
REPORTING_ENABLE="y"
REPORTING_EMAILS="example@example.com"
